# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951f96333b3a9d721c0092bb4670e65f692b767796102d0bf895114ad8aba721b3c6ca8af823f07d1d4491cae1671857a35a227bdd428d5e488d3ae90721b5a0

test:
  secret_key_base: 138c5b5f6a8ae8cbf27e2621a7f55d8993414253db31704387cb666ead33dde05bc05c037d16ec81798e983d68ec43e1fde24ce8c3ed1e5f2cb681281ff80ecb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
